package com.goodsbyus

import android.graphics.Color

data class ColorModel (
    val colorText: String,
    val colorString: String) {
    companion object {
        val colorList = listOf(
            ColorModel("red", "#FF0000"),
            ColorModel("crimson", "#DC143C"),
            ColorModel("firebrick", "#B22222"),
            ColorModel("maroon", "#800000"),
            ColorModel("darkred", "#8B0000"),
            ColorModel("brown", "#A52A2A"),
            ColorModel("sienna", "#A0522D"),
            ColorModel("saddlebrown", "#8B4513"),
            ColorModel("indianred", "#CD5C5C"),
            ColorModel("rosybrown", "#BC8F8F"),
            ColorModel("lightcoral", "#F08080"),
            ColorModel("salmon", "#FA8072"),
            ColorModel("darksalmon", "#E9967A"),
            ColorModel("coral", "#FF7F50"),
            ColorModel("tomato", "#FF6347"),
            ColorModel("sandybrown", "#F4A460"),
            ColorModel("lightsalmon", "#FFA07A"),
            ColorModel("peru", "#CD853F"),
            ColorModel("chocolate", "#D2691E"),
            ColorModel("orangered", "#FF4500"),
            ColorModel("orange", "#FFA500"),
            ColorModel("darkorange", "#FF8C00"),
            ColorModel("tan", "#D2B48C"),
            ColorModel("peachpuff", "#FFDAB9"),
            ColorModel("bisque", "#FFE4C4"),
            ColorModel("moccasin", "#FFE4B5"),
            ColorModel("navajowhite", "#FFDEAD"),
            ColorModel("wheat", "#F5DEB3"),
            ColorModel("burlywood", "#DEB887"),
            ColorModel("darkgoldenrod", "#B8860B"),
            ColorModel("goldenrod", "#DAA520"),
            ColorModel("gold", "#FFD700"),
            ColorModel("yellow", "#FFFF00"),
            ColorModel("lightgoldenrodyellow", "#FAFAD2"),
            ColorModel("palegoldenrod", "#EEE8AA"),
            ColorModel("khaki", "#F0E68C"),
            ColorModel("darkkhaki", "#BDB76B"),
            ColorModel("lawngreen", "#7CFC00"),
            ColorModel("greenyellow", "#ADFF2F"),
            ColorModel("chartreuse", "#7FFF00"),
            ColorModel("lime", "#00FF00"),
            ColorModel("limegreen", "#32CD32"),
            ColorModel("yellowgreen", "#9ACD32"),
            ColorModel("olive", "#808000"),
            ColorModel("olivedrab", "#6B8E23"),
            ColorModel("darkolivegreen", "#556B2F"),
            ColorModel("forestgreen", "#228B22"),
            ColorModel("darkgreen", "#006400"),
            ColorModel("green", "#008000"),
            ColorModel("seagreen", "#2E8B57"),
            ColorModel("mediumseagreen", "#3CB371"),
            ColorModel("darkseagreen", "#8FBC8F"),
            ColorModel("lightgreen", "#90EE90"),
            ColorModel("palegreen", "#98FB98"),
            ColorModel("springgreen", "#00FF7F"),
            ColorModel("mediumspringgreen", "#00FA9A"),
            ColorModel("teal", "#008080"),
            ColorModel("darkcyan", "#008B8B"),
            ColorModel("lightseagreen", "#20B2AA"),
            ColorModel("mediumaquamarine", "#66CDAA"),
            ColorModel("cadetblue", "#5F9EA0"),
            ColorModel("steelblue", "#4682B4"),
            ColorModel("aquamarine", "#7FFFD4"),
            ColorModel("powderblue", "#B0E0E6"),
            ColorModel("paleturquoise", "#AFEEEE"),
            ColorModel("lightblue", "#ADD8E6"),
            ColorModel("lightsteelblue", "#B0C4DE"),
            ColorModel("skyblue", "#87CEEB"),
            ColorModel("lightskyblue", "#87CEFA"),
            ColorModel("mediumturquoise", "#48D1CC"),
            ColorModel("turquoise", "#40E0D0"),
            ColorModel("darkturquoise", "#00CED1"),
            ColorModel("aqua", "#00FFFF"),
            ColorModel("cyan", "#00FFFF"),
            ColorModel("deepskyblue", "#00BFFF"),
            ColorModel("dodgerblue", "#1E90FF"),
            ColorModel("cornflowerblue", "#6495ED"),
            ColorModel("royalblue", "#4169E1"),
            ColorModel("blue", "#0000FF"),
            ColorModel("mediumblue", "#0000CD"),
            ColorModel("navy", "#000080"),
            ColorModel("darkblue", "#00008B"),
            ColorModel("midnightblue", "#191970"),
            ColorModel("darkslateblue", "#483D8B"),
            ColorModel("slateblue", "#6A5ACD"),
            ColorModel("mediumslateblue", "#7B68EE"),
            ColorModel("mediumpurple", "#9370DB"),
            ColorModel("darkorchid", "#9932CC"),
            ColorModel("darkviolet", "#9400D3"),
            ColorModel("blueviolet", "#8A2BE2"),
            ColorModel("mediumorchid", "#BA55D3"),
            ColorModel("plum", "#DDA0DD"),
            ColorModel("lavender", "#E6E6FA"),
            ColorModel("thistle", "#D8BFD8"),
            ColorModel("orchid", "#DA70D6"),
            ColorModel("violet", "#EE82EE"),
            ColorModel("indigo", "#4B0082"),
            ColorModel("darkmagenta", "#8B008B"),
            ColorModel("purple", "#800080"),
            ColorModel("mediumvioletred", "#C71585"),
            ColorModel("deeppink", "#FF1493"),
            ColorModel("fuchsia", "#FF00FF"),
            ColorModel("magenta", "#FF00FF"),
            ColorModel("hotpink", "#FF69B4"),
            ColorModel("palevioletred", "#DB7093"),
            ColorModel("lightpink", "#FFB6C1"),
            ColorModel("pink", "#FFC0CB"),
            ColorModel("mistyrose", "#FFE4E1"),
            ColorModel("blanchedalmond", "#FFEBCD"),
            ColorModel("lightyellow", "#FFFFE0"),
            ColorModel("cornsilk", "#FFF8DC"),
            ColorModel("antiquewhite", "#FAEBD7"),
            ColorModel("papayawhip", "#FFEFD5"),
            ColorModel("lemonchiffon", "#FFFACD"),
            ColorModel("beige", "#F5F5DC"),
            ColorModel("linen", "#FAF0E6"),
            ColorModel("oldlace", "#FDF5E6"),
            ColorModel("lightcyan", "#E0FFFF"),
            ColorModel("aliceblue", "#F0F8FF"),
            ColorModel("whitesmoke", "#F5F5F5"),
            ColorModel("lavenderblush", "#FFF0F5"),
            ColorModel("floralwhite", "#FFFAF0"),
            ColorModel("mintcream", "#F5FFFA"),
            ColorModel("ghostwhite", "#F8F8FF"),
            ColorModel("honeydew", "#F0FFF0"),
            ColorModel("seashell", "#FFF5EE"),
            ColorModel("ivory", "#FFFFF0"),
            ColorModel("azure", "#F0FFFF"),
            ColorModel("snow", "#FFFAFA"),
            ColorModel("white", "#FFFFFF"),
            ColorModel("gainsboro", "#DCDCDC"),
            ColorModel("lightgrey", "#D3D3D3"),
            ColorModel("silver", "#C0C0C0"),
            ColorModel("darkgray", "#A9A9A9"),
            ColorModel("lightslategray", "#778899"),
            ColorModel("slategray", "#708090"),
            ColorModel("gray", "#808080"),
            ColorModel("dimgray", "#696969"),
            ColorModel("darkslategray", "#2F4F4F"),
            ColorModel("black", "#000000")
        )
    }
    val color get() = Color.parseColor(colorString)
}




